name = "abate"
compatibility_date = "2024-05-04" # Use a data de hoje ou mais recente
pages_build_output_dir = ".vercel/output/static" # Diretório de saída como texto
compatibility_flags = ["nodejs_compat"] # Flag como texto dentro de uma lista
